---
title: "Cuyama Analysis"
author: "Madeline Gorchels"
date: "3/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Part 1: Ground Water Levels in the Cuyama Basin

```{r, include = FALSE}
library(tidyverse)
library(knitr)
library(forecast)
library(sf)
library(leaflet)
library(ggrepel)
library(ggspatial)
library(RColorBrewer)
library(maptools)
library(sp)
library(gstat)
library(raster)
```


```{r, include=FALSE}
#Santa Barbara County, California
#Hydrologic Unit Code 18060007
#Latitude  34°56'03.7", Longitude 119°41'23.4" NAD83
#Land-surface elevation 2,155 feet above NGVD29
#The depth of the well is 790 feet below land surface.
#The depth of the hole is 820 feet below land surface.
#This well is completed in the California Coastal Basin aquifers (N100CACSTL) national aquifer.

well1_wl = read_csv("well1_wl.csv") %>% 
  mutate(neg_dep = water_level*-1) %>% 
  dplyr::select(date, water_level, neg_dep) %>% 
  filter(date != "NA")
```

Water levels in one well from 1981 to present 
```{r}
ggplot(well1_wl)+
  geom_point(aes(x = date, y = neg_dep))+
  theme_classic()+
  labs(y = "Depth to water level, feet below land surface", x = "Year")
```

###Part 2: Subsidence 
```{r, echo = FALSE}
#OPTI Well #895 Latitude: 34.68337136 Longitude: -119.3534074
#OPTI Well #896 Latitude: 34.88856804 Longitude: -119.8153558
#OPTI Well #897 Latitude: 34.9426 Longitude: -119.6739
#OPTI Well #898 Latitude: 34.8515 Longitude: -119.4839
#OPTI Well #899 Latitude: 34.9205 Longitude: -119.4058
```



###Part 3: Water Quality Concerns

```{r, echo=FALSE, message=FALSE, output=FALSE}
#spatial information for well1 same as the ground water levels
well1_wq = read_csv("well1_wq.csv") %>% 
  mutate(TDS = Calcium + Na + Mg + K + Cl + Fl + SO4)
```

```{r}
ggplot(data = well1_wq)+ 
  geom_point(aes(x = date, y = solids))+
  theme_classic()+
  geom_point(aes(x = date, y = NO4), color = "blue")+
  scale_y_continuous(sec.axis = sec_axis(~./1000, name = "Nitrate (mg/L)"))
```
Loading of the Cuyama Polygon
```{r}
cuyama = read_sf(".", layer = "Cuyama_Groundwater_Basin-polygon")
st_crs(cuyama) = 4326
```

Time to mess with it 
```{r}
plot(cuyama)
ggplot(cuyama)+
  geom_sf()


leaflet(cuyama) %>% 
  addTiles() %>% 
  addPolygons()
```

```{r}
nitrate = read_csv("tds_initial.csv") %>% 
  #dplyr::select(-X6, -X7, -X8) %>% 
  group_by(Site_Name) %>% 
  mutate(Date = as.Date(Date, "%m/%d/%Y")) %>% 
  mutate(year = as.numeric(format(Date,'%Y')))
  

nitrate_sf = st_as_sf(nitrate, coords = c("Longitude", "Latitude"), crs = 4326)

cuyama_sp = as(cuyama, "Spatial") 
cuyama_win = as(cuyama_sp, "owin")

```


```{r}
tm_shape(cuyama)+
  tm_fill()+
  tm_shape(nitrate_sf)+
  tm_dots("NO3", size = 0.5) 
```
```{r}
nitrate_sp = as_Spatial(nitrate_sf)

lat <- seq(35.24, 35.26, length.out = 200)
long <- seq(-120.15,-120.21, length.out = 200)

grid = expand.grid(lon = long, lat = lat)
grid_sf = st_as_sf(grid, coords = c("lon", "lat"), crs = 4326) #converts to simple feature object
grid_sp = as_Spatial(grid_sf)
```

Variogram creation 
```{r}
nitrate_vg = gstat::variogram(NO3~1, data = nitrate_sp)
plot(nitrate_vg)
nitrate_vgm_fit <- fit.variogram(nitrate_vg, model = vgm(nugget = 0, psill = 5, model = "Sph", range = 10))

```
Kriging

```{r}
nitrate_krige <- krige(NO3 ~ 1, nitrate_sp, grid_sp, model=nitrate_vgm_fit)
```
Kriging visualization 
```{r}
nitrate_krige_df = as.data.frame(nitrate_krige)
nitrate_krige_2 = nitrate_krige_df %>% 
  rename(lon = coords.x1, lat = coords.x2, predicted = var1.pred, err = var1.var)
nitrate_predicted = st_as_sf(nitrate_krige_2, coords = c("lon", "lat"), crs = 4326)

plot(nitrate_predicted)

nitrate_cropped = st_intersection(rain_predicted, nitrate)
plot(nitrate_cropped)
```


Nitrate concentration in 1990
```{r}
nitrate_1966_sf = nitrate_sf %>% 
  filter(year == 1966)
 
```


```{r}
nitrate_1966_sp = as_Spatial(nitrate_1966_sf)

```

Variogram creation 
```{r}
nitrate_1966_vg = gstat::variogram(NO3~1, data = nitrate_1966_sp)
#plot(nitrate_1991_vg)
nitrate_vgm_1966_fit <- fit.variogram(nitrate_1966_vg, model = vgm(nugget = 0, psill = 5, model = "Sph", range = 1))

```
Kriging

```{r}
nitrate_1966_krige <- krige(NO3 ~ 1, nitrate__sp, grid_sp, model=nitrate_vgm_1966_fit)


nitrate_krige_df_1966 = as.data.frame(nitrate_1966_krige)
nitrate_krige_2_1966 = nitrate_krige_df_1966 %>% 
  rename(lon = coords.x1, lat = coords.x2, predicted = var1.pred, err = var1.var)
nitrate_predicted = st_as_sf(nitrate_krige_2, coords = c("lon", "lat"), crs = 4326)

plot(nitrate_predicted)

nitrate_cropped = st_intersection(nitrate_predicted, nitrate)
plot(nitrate_cropped)
```

Trying to find where the most nitrate data is found
```{r}
nitrate_count = nitrate_sf %>% 
  group_by(year) %>% 
  tally() %>% 
  arrange(-n) %>% 
  head(25)

ggplot(nitrate_count)+
  geom_sf(data = cuyama)+
  geom_sf(data = nitrate_count)+
  theme_minimal()
  
```

